language: go
go:
- 1.x
- '1.10'
- 1.11.x
- master
deploy:
  provider: heroku
  api_key:
    secure: IJAZc5xp5j4ZazpKTLTXQlP1CrLFtshxBmex00451Neu6cDJk0U2+E7ItK8qrca/hfQ7O30FAyTRSf6ZWAvOoJF3tZ0OyC6QJgx74+9n7pA1/F4DdlE7pWRGikAmmistloKHPTAjgE4BJ0B5idGoRRsFppf8cxOhMDbe3uSFGaydhxNpvw0zvk3GjY6MtbJ/VPVmiUQlifQUTOaf+U2h85Hz4PJjxF3tPf17mS8tdHNGiQwuLthP/s9YJNJoqk2F8ZgEgCGL2gUIeTgvO7ywna+v6KQb0NAarIquyVvyCFTsQMF0eI5+O2t2lZaL4y1orEdj5Mi7Cdjr+xT+TCszq8sHQU3SoaW6WNPCGevEROg4asM5H4iWqfDMbp/eijBfY/o9EseLCBhJC9VXNs9TCk1E40PzwHYs27BAw+vdYfOLj2ZejGTMo6OmCa1HVsUVvLGSfvzdoe8KdKbLizQuOCJBZoDj4lxPPBPTnSydWVTqBgNrzF9YseTjHwSExRtHVMTNT4lxobLKZ1JD9VEFB2eKjv8JPkLHehooCDojHK6gEcWaqT3/uhw5UYFVPqljvLQDikmp01QTxjqr8K/bquhHD93Fx2YL8ZJa/iM9sv0V8h+6NxklICKo5f+Y51Kkuzsvx2QidtlXsdF9PBCzud7hfOyzZZXGBLMfUScNTvM=
  app: vast-taiga-96506