language: go
go:
- 1.14.x
- master
deploy:
  provider: heroku
  api_key:
    secure: FN2lBVR+jy1wEloogQ4sdXgUG2kHvbUw5dCEe2Rs14qTFUe9ckK95TonNzsoVz6lF7OTrjiYlxX/WneSzUvGlXd7ht5Uk511IbYY1n6GDwK5Ulk6XPrwxdX5ibh9RfiLBN2MlQtb4Monx+DPNYIwJHcrMjIMtqC/IWIeeKBNBXjDl1Uj8utazbQAtUDdqYpKlMOPAhsgYALEbZX/B8Dz/ei41OpoQ/SSS1zrbYIDFD0umjFz2ao4eHdAqnagDDcmIE1iRsdgiHM70A+K/pVSqR0tamFvfzkIQPonZSxqbVlM0yMZzfasEvPqLcHcQ/tFZTwGLsDTtQF9rvk0BS21RKw75IJEJvLrtd+O+58fKzBEjUgsum5zwD2aW/jzUEuMH+cXPLdW2dcgHYE9sdJqB2bSJ1J99sMXF/rxYwUuYmJfr5+YS0a0Qt5RR8o7V3g31ZOkSuAD0G6BB6f9iw4Sbr2+rBoGkbykho3c8pAbB0ll8/BEQjE0T+25v81kr1oW5c2+utFSLWI1DZDwdJT4EvxCgy2o4anemqr4zhPTwRcmNN94Ri7dcMjCEqDESyUQdPfCJOGFBzuuCUC2baLaTIod/k8elUrU6OqWpJyx+NLeaJSyfgeas+MoVKZ6KTRP1FJsBdO20tnwktHNQ3++7ZHgPpdvHjoACubryVK0FaI=
  app: vast-taiga-96506
