language: go
go:
- 1.x
- '1.10'
- 1.11.x
- master
deploy:
  provider: heroku
  api_key:
    secure: PDUF8IoqztGWzYxiLG0fIEfQDDh+bNlFfUjLhSu4wqQwu0BA9oT19f8srlMD5i2OaR46A/lotBuw1onR5EEKVZpIOP+3n9+aiS6p8+rVXjBcet2ElZNnvf1aXZEEFEexZ2ykUOgxULT0NnCWpVvhUnNIiN/DZZ1r2lq7FdAHqafi2miDRUddhu+D+BENaN0G8kNOPgAGhd95klT0dgtLoXMWWAGk6wZU0IapjnEtAR4MojH0botedEZTyWe59eutgYDOQuQo7HYpTNUM8KWIFeGv5fWAbDpwQdJCdFmhm979z91+ts84tKbgM4VLZ3j8WlkzUc3XPe9YnHFuxdQDbheOlArzRHJImNHojTPiB3Rldl5PYg9lF4Mf14IWibKVMsi5S8zkuDLFRAvPFfsP+y8JbDmsDmnOEZ3RByLr3mxPyNLOZXMcnOZIL1RZIDtBgyB6XKhsvPyF2g/jOQGf5ZBbHMQs7bTeK14yPJPN4l3W8U+9B8ypAAlQdtt9vErKPSvzjGNzioK1DzaQVS8UjRwh9z/HMSp9MbkmNqX+CztTo5PNRrRnOLnBHrxU/CL2RS1VMNiSDOi/4KXTSuLuxaLV/xPO1Mq1CqVzF0afW/nzTRSO8b2/Ts+2YYq1gOyvirg3hhhXvsfIS7cg1OIeuAUgPZPrh5RNFetpHxKSLIg=
  app: vast-taiga-96506
